livestream_id: jfKfPfyJRdk

obs_auth:
  host: localhost
  port: 4455
  password: cYiHY0HBsyzvVwPQ

obs_scene_settings:
  scene_name: test scene
  case_input_names:
    - Case1
    - Case2
    - Case3
    - Case4
    - Case5

selection_plot_filepath: G:\OBS Projects\demo project\plot.png
plot_refresh_rate: 1 #milliseconds